import net.minecraftforge.gradle.userdev.tasks.JarJar

plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '[1,2)'
    id 'org.spongepowered.mixin' version '[0.7,0.8)'
    id 'org.moddingx.modgradle.mapping' version '[4,5)'
    id 'org.moddingx.modgradle.sourcejar' version '[4,5)' apply false
    id 'com.matthewprenger.cursegradle' version '1.4.0' apply false
    id 'com.modrinth.minotaur' version '[2,)' apply false
}

// This initializes the config. Please try to modify the variables in the config file, if needed, add more if you see a reason to.
ext.config = parseConfig(file('build.properties'))

version = config.VERSION
group = "${config.GROUP}.${config.ARTIFACT}"
base.archivesName = "${config.ARCHIVES_BASE_NAME}-${config.MINECRAFT_VERSION}"

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

apply plugin: 'org.moddingx.modgradle.sourcejar'

minecraft {
    mappings channel: config.MAPPINGS_CHANNEL, version: config.MAPPINGS_VERSION

    //enableEclipsePrepareRuns = true
    //enableIdeaPrepareRuns = true

    copyIdeResources = true

    //generateRunFolders = true

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                infernalexp {
                    source sourceSets.main
                }
            }
        }

        client { }

        server {
            args '--nogui'
        }

        data {
            args '--mod', 'infernalexp', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

mixin {
    add sourceSets.main, "infernal-expansion.refmap.json"
    config 'infernal-expansion.mixins.json'

    debug.verbose = true
    debug.export = true
    dumpTargetOnFailure = true
}

repositories {
    maven { url = 'https://repo.spongepowered.org/maven/' }

    // Crystal Nest repository where Soul Fire'd is hosted.
    maven {
        name = "Crystal Nest"
        url = "https://maven.crystalnest.it"
    }
    // Fuzs repository where Soul Fire'd required dependency FCAP is hosted.
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${config.MINECRAFT_VERSION}-${config.FORGE_VERSION}"
    annotationProcessor "org.spongepowered:mixin:${config.MIXIN_VERSION}:processor"

    // MixinExtras
    // This is included with Soul Fire'd, so we don't need to embed it ourselves
    compileOnly annotationProcessor("io.github.llamalad7:mixinextras-common:${config.MIXINEXTRAS_VERSION}")
    implementation "io.github.llamalad7:mixinextras-forge:${config.MIXINEXTRAS_VERSION}"

    // TerraBlender
    compileOnly fg.deobf("com.github.glitchfiend:TerraBlender-forge:${config.MINECRAFT_VERSION}-${config.TERRABLENDER_VERSION}")

    // Soul Fire'd
    implementation(jarJar(fg.deobf("it.crystalnest:cobweb-forge:${config.MINECRAFT_VERSION}-${config.COBWEB_VERSION}"))) {
        jarJar.pin(it, config.COBWEB_VERSION)
        jarJar.ranged(it, "[${config.COBWEB_VERSION},)")
    }
    implementation(jarJar(fg.deobf("it.crystalnest:soul-fire-d-forge:${config.MINECRAFT_VERSION}-${config.SOUL_FIRE_D_VERSION}"))) {
        jarJar.pin(it, config.SOUL_FIRE_D_VERSION)
        jarJar.ranged(it, "[${config.SOUL_FIRE_D_VERSION},)")
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'   : config.TITLE,
                'Specification-Vendor'  : config.AUTHOR,
                'Specification-Version' : '1',
                'Implementation-Title'  : config.TITLE,
                'Implementation-Version': config.VERSION,
                'Implementation-Vendor' : config.AUTHOR
        ])
    }

    finalizedBy('reobfJar')

    archiveClassifier = 'no-embeds'
}

tasks.named('jarJar', JarJar).configure {
    finalizedBy 'reobfJarJar'

    archiveClassifier = ''
}

tasks.named('build', DefaultTask).configure {
    dependsOn 'jarJar'
}

afterEvaluate {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        defaultCharacterEncoding = 'UTF-8'
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = config.GROUP
            artifactId = config.ARTIFACT
            artifact project.tasks.jarJar
            artifact jar
            artifact sourceJar
            version "${config.VERSION}-${config.MINECRAFT_VERSION}"

            pom {
                name = 'Infernal Expansion'
                url = 'https://infernalstudios.org/infernalexp'
                licenses {
                    license {
                        name = 'Apache License 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/infernalexp/Infernal-Expansion.git'
                    url = 'https://github.com/infernalexp/Infernal-Expansion'
                }
            }
        }
    }
    repositories {
        maven {
            url 'https://maven.infernalstudios.org/releases'
            
            credentials {
                username = System.getenv('MAVEN_USER')
                password = System.getenv('MAVEN_TOKEN')
            }
            
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

if (System.getenv('MODRINTH')) {
    apply plugin: 'com.modrinth.minotaur'

    // Modrinth publishing
    modrinth {
        token = System.getenv('MODRINTH')
        projectId = 'ZrpxHZN4'
        versionNumber = project.version
        versionType = "release"
        uploadFile = project.tasks.jarJar
        additionalFiles = [ jar, sourceJar ]
        gameVersions = [ config.MINECRAFT_VERSION ]
        loaders = [ 'forge' ]
    }
} else {
    logger.lifecycle 'Disabling Modrinth publishing! MODRINTH environment variable is not set.'
}

if (System.getenv('CURSEFORGE')) {
    apply plugin: 'com.matthewprenger.cursegradle'

    // Curseforge publishing
    curseforge {
        apiKey = System.getenv('CURSEFORGE') ?: 'If you\'re seeing this, you haven\'t set your "CURSEFORGE" environment variable'

        project {
            id = '395078'
            changelog = 'No changelog specified.'
            releaseType = 'release'
            addGameVersion config.MINECRAFT_VERSION
            mainArtifact (project.tasks.jarJar) {
                displayName = "Infernal Expansion Release ${project.version}"
            }
            addArtifact jar
            addArtifact sourceJar
        }
    }
} else {
    logger.lifecycle 'Disabling CurseForge publishing! CURSEFORGE environment variable is not set.'
}


// Config parse function
def parseConfig(File config) {
    config.withReader {
        def prop = new Properties()
        prop.load(it)
        return (new ConfigSlurper().parse(prop))
    }
}

idea.module {
    // IntelliJ IDEA does not do this by itself anymore...
    downloadJavadoc = downloadSources = true
}
